### ISSUE TITLE
Create @types/string-mismatch project for compatibility with TypeScript project like Angular

### ISSUE THREAD

**Issue by wil92** [wil92/string-mismatch#13]

**Comment by dandellicarri** [comment]
Is this [the project](https://github.com/wil92/-types-string-mismatch) you were going to create? If so, you can close this issue. Also, I see you've been using this issue form as a to-do list, so why wouldn't you instead create a ROADMAP file for that?

**Comment by wil92** [comment]
I will take the ROADMAP into consideration, thx for the suggestion. About the (wil92/-types-string-mismatch) project, it was in did the first try to create the @type definition for the library, but in the end, this is not needed, because there is a different way to do that, this is still a work in progress and it will come with other updates in the library.
