### ISSUE TITLE
Substitution type not being recognized

### ISSUE THREAD

**Issue by aoor9** [wil92/string-mismatch#17]
According to the example on the README file (and I tested it too),
```
var start = 'This is a test for see how work the library',
    end   = 'This is a test for know how work the new library';

console.log(showResult(greedyInstance.differences(start, end)));
/*
result:
This is a test for (-see)(+know) how work the (+new )library
*/
```
The _see_ and _know_ words are detected as _deletion_ and _insertion_. Aren't they both supposed to be under the _substitution_ type, as they are placed on the same position in the string, between equal portions?
`This is a test for (-+see,know) how work the (+new )library`

**Comment by wil92** [comment]
If you check the initial table where the algorithms are compared, you can see that the operations available for the Gready algorithm are only: insert and delete, the substitution is only available in the Levenshtein algorithm.

Sorry for the late reply.
